# Generated by Django 5.2.15 on 2026-06-27 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditlog"),
        ("statements", "0008_seed_autopay_and_bank_narration_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeminiUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                "transaction_categorize_parse",
                                "Categorize transactions (statement parse)",
                            ),
                            (
                                "transaction_categorize_manual",
                                "Categorize transactions (manual AI)",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("rate_limited", "Rate limited"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("model", models.CharField(max_length=128)),
                ("merchants_in_batch", models.PositiveIntegerField(default=0)),
                ("transactions_updated", models.PositiveIntegerField(default=0)),
                (
                    "prompt_token_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "candidates_token_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "cached_content_token_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "thoughts_token_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "tool_use_prompt_token_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_token_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "response_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "model_version",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("usage_metadata", models.JSONField(blank=True, default=dict)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Caller context such as merchant keys and statement ids.",
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gemini_usage_logs",
                        to="statements.statement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gemini_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_gemini_user_id_33f921_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_gemini_action_864200_idx",
                    ),
                    models.Index(
                        fields=["user", "action", "-created_at"],
                        name="core_gemini_user_id_a1c962_idx",
                    ),
                ],
            },
        ),
    ]
