# Generated by Django 5.2.15 on 2026-06-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0005_seed_system_category_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("csv", "CSV"),
                    ("pdf", "PDF"),
                    ("xls", "XLS"),
                    ("xlsx", "XLSX"),
                ],
                max_length=8,
            ),
        ),
    ]
