# Generated by Django 5.2.15 on 2026-06-27 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normalized_merchant", models.CharField(max_length=512)),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("autopay", "Autopay"),
                            ("emi", "EMI"),
                            ("loan", "Loan"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "amount_variance_pct",
                    models.FloatField(
                        default=0.0,
                        help_text="Percent deviation of amounts from the mean.",
                    ),
                ),
                ("next_expected_date", models.DateField(blank=True, null=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["normalized_merchant"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="analysis_re_user_id_003cde_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "normalized_merchant", "pattern_type"),
                        name="unique_user_merchant_pattern_type",
                    )
                ],
            },
        ),
    ]
